package com.example.medicinereminderapp

import java.util.Date

class TimeModel(val hour: Int, val minute: Int)

class Medicine {
    var name: String = ""
    var xTimes: Int = -1
    var times: MutableList<TimeModel> = mutableListOf()
    var startDate : Date = Date()
    var endDate : Date = Date()
}

class ReportData(
    var id: Long = -1, // Set to -1 for new entries, generated by the database
    var medicineName: String = "",
    var dateTime: Date = Date(),
    var isTaken: Boolean = false
)